fix(get_make_error_fn): latest msvc does not work with and_then
D:\a\monadics\monadics\include\beman/monadics/detail/get_make_error_fn.hpp(18): error C2440: 'return': cannot convert from 'beman::monadics::tests::`anonymous-namespace'::Foo *' to '_T9 &&'
        with
        [
            _T9=nullptr
        ]
D:\a\monadics\monadics\include\beman/monadics/detail/get_make_error_fn.hpp(18): note: Reason: cannot convert from 'beman::monadics::tests::`anonymous-namespace'::Foo *' to '_T9'
        with
        [
            _T9=nullptr
        ]
D:\a\monadics\monadics\include\beman/monadics/detail/get_make_error_fn.hpp(18): note: nullptr can only be converted to pointer or handle types
D:\a\monadics\monadics\include\beman/monadics/detail/get_make_error_fn.hpp(18): note: the template instantiation context (the oldest one first) is
D:\a\monadics\monadics\tests\beman\monadics\raw_ptr\and_then.test.cpp(32): note: see reference to function template instantiation 'beman::monadics::tests::`anonymous-namespace'::Foo *beman::monadics::detail::operator |